import Foundation
@_exported @preconcurrency import GRDB
import StorageCore

public protocol StorageKitEntityRecord: FetchableRecord, PersistableRecord, Sendable {
    associatedtype E: StorageKitEntity
    static var databaseTableName: String { get }
    func asEntity() -> E
    static func from(_ e: E, now: Date) -> Self

    /// Schema columns for auto-migration support
    /// Generated by @StorageEntity macro
    static var schemaColumns: [ColumnSchema] { get }
}

// Default implementation for backward compatibility
extension StorageKitEntityRecord {
    public static var schemaColumns: [ColumnSchema] { [] }
}
